### ISSUE TITLE
entering  initialState doesn't trigger onEntry  

### ISSUE THREAD

**Issue by sorokod** [oxo42/stateless4j#46] opened 2015-09-28 14:19 UTC
When the StateMachine enters the initialState by invoking `StateMachine(S initialState, StateMachineConfig<S, T> config)` the `onEntry` action is not executed. On the other hand, when the intialState is exited, the `onExit` action is executed.

It makes sense for both `onEntry` and `onExit` to be executed in this case.

**Comment by aytchell** [comment] 2016-06-09 13:52
Isn't this a duplicate of #30 (which is already fixed)?

**Closed** 2018-05-09 23:56 UTC
